apiVersion: v1
kind: Service
metadata:
  name: kubernetes-resource-manager-backend-service
  labels:
    app: kubernetes-resource-manager-backend
spec:
  type: NodePort
  selector:
    app: kubernetes-resource-manager-backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
  sessionAffinity: None 